name: Backend Build Workflow

on:
  push:
    branches:
      - main
#    paths:
#      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: ./starter/backend

      - name: Lint Using Flake
        run: pipenv run flake8 .
        working-directory: ./starter/backend

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pipenv
        run: pip install pipenv  # Install pipenv if it's not already available

      - name: Install dependencies
        run: pipenv install --dev  # Install all dependencies from Pipfile.lock
        working-directory: ./starter/backend

      - name: Run Unit Tests
        run: pipenv run test
        working-directory: ./starter/backend

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker buildx build --load --tag backend:${{ github.sha }} .
        working-directory: ./starter/backend
