name: Frontend Deploy Workflow

on:
  push: # pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository xx
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend

      - name: Test
        run: |
          npm run lint
        working-directory: ./starter/frontend

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker buildx build --load --tag my-image:${{ github.sha }} .
        working-directory: ./starter/frontend
      - name: Test
        run: |
          npm run lint
        working-directory: ./starter/frontend

#  push:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v3
#
#      - name: Configure AWS credentials
#        uses: actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#          aws-region: us-east-1
